// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ru.kamenetskii.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializegetByIdResponse")
public inline fun getByIdResponse(block: ru.kamenetskii.yarns.api.v1.service.GetByIdResponseKt.Dsl.() -> kotlin.Unit): ru.kamenetskii.yarns.api.v1.service.GetByIdResponse =
  ru.kamenetskii.yarns.api.v1.service.GetByIdResponseKt.Dsl._create(ru.kamenetskii.yarns.api.v1.service.GetByIdResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ru.kamenetskii.yarns.api.v1.service.GetByIdResponse`
 */
public object GetByIdResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ru.kamenetskii.yarns.api.v1.service.GetByIdResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ru.kamenetskii.yarns.api.v1.service.GetByIdResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ru.kamenetskii.yarns.api.v1.service.GetByIdResponse = _builder.build()

    /**
     * `.ru.kamenetskii.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     */
    public var user: ru.kamenetskii.yarns.api.v1.entity.User
      @kotlin.jvm.JvmName("getUser")
        get() = _builder.user
      @kotlin.jvm.JvmName("setUser")
        set(value) {
        _builder.user = value
      }
    /**
     * `.ru.kamenetskii.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     */
    public fun clearUser() {
      _builder.clearUser()
    }
    /**
     * `.ru.kamenetskii.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     * @return Whether the user field is set.
     */
    public fun hasUser(): kotlin.Boolean {
      return _builder.hasUser()
    }

    public val GetByIdResponseKt.Dsl.userOrNull: ru.kamenetskii.yarns.api.v1.entity.User?
      get() = _builder.userOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ru.kamenetskii.yarns.api.v1.service.GetByIdResponse.copy(block: `ru.kamenetskii.yarns.api.v1.service`.GetByIdResponseKt.Dsl.() -> kotlin.Unit): ru.kamenetskii.yarns.api.v1.service.GetByIdResponse =
  `ru.kamenetskii.yarns.api.v1.service`.GetByIdResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ru.kamenetskii.yarns.api.v1.service.GetByIdResponseOrBuilder.userOrNull: ru.kamenetskii.yarns.api.v1.entity.User?
  get() = if (hasUser()) getUser() else null

