// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package ru.kamenetskii.yarns.api.v1.service;

@com.google.protobuf.Generated
public final class ServiceProto {
  private ServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030v1/service/service.proto\022#ru.kamenetsk" +
      "ii.yarns.api.v1.service\032\024v1/entity/user." +
      "proto\"/\n\017RegisterRequest\022\034\n\tpublicKey\030\001 " +
      "\001(\014R\tpublicKey\"P\n\020RegisterResponse\022<\n\004us" +
      "er\030\001 \001(\0132(.ru.kamenetskii.yarns.api.v1.e" +
      "ntity.UserR\004user\"(\n\016GetByIdRequest\022\026\n\006us" +
      "erId\030\001 \001(\003R\006userId\"O\n\017GetByIdResponse\022<\n" +
      "\004user\030\001 \001(\0132(.ru.kamenetskii.yarns.api.v" +
      "1.entity.UserR\004user2\373\001\n\nYarnsApiV1\022w\n\010Re" +
      "gister\0224.ru.kamenetskii.yarns.api.v1.ser" +
      "vice.RegisterRequest\0325.ru.kamenetskii.ya" +
      "rns.api.v1.service.RegisterResponse\022t\n\007G" +
      "etById\0223.ru.kamenetskii.yarns.api.v1.ser" +
      "vice.GetByIdRequest\0324.ru.kamenetskii.yar" +
      "ns.api.v1.service.GetByIdResponseBa\n#ru." +
      "kamenetskii.yarns.api.v1.serviceB\014Servic" +
      "eProtoP\001Z*github.com/yarns-pro/api/pkg/g" +
      "o/v1/serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.kamenetskii.yarns.api.v1.entity.EntityProto.getDescriptor(),
        });
    internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterRequest_descriptor,
        new java.lang.String[] { "PublicKey", });
    internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_kamenetskii_yarns_api_v1_service_RegisterResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_kamenetskii_yarns_api_v1_service_GetByIdResponse_descriptor,
        new java.lang.String[] { "User", });
    descriptor.resolveAllFeaturesImmutable();
    ru.kamenetskii.yarns.api.v1.entity.EntityProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
