// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/entity/message_metadata.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Filesize      int64                  `protobuf:"varint,3,opt,name=filesize,proto3" json:"filesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMetadata) Reset() {
	*x = MessageMetadata{}
	mi := &file_v1_entity_message_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMetadata) ProtoMessage() {}

func (x *MessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_entity_message_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMetadata.ProtoReflect.Descriptor instead.
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return file_v1_entity_message_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MessageMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MessageMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MessageMetadata) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

var File_v1_entity_message_metadata_proto protoreflect.FileDescriptor

const file_v1_entity_message_metadata_proto_rawDesc = "" +
	"\n" +
	" v1/entity/message_metadata.proto\x12\x17pro.yarns.api.v1.entity\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\x0fMessageMetadata\x12\x1a\n" +
	"\bmimeType\x18\x01 \x01(\tR\bmimeType\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfilesize\x18\x03 \x01(\x03R\bfilesizeB+Z)github.com/yarns-pro/api/pkg/go/v1/entityb\x06proto3"

var (
	file_v1_entity_message_metadata_proto_rawDescOnce sync.Once
	file_v1_entity_message_metadata_proto_rawDescData []byte
)

func file_v1_entity_message_metadata_proto_rawDescGZIP() []byte {
	file_v1_entity_message_metadata_proto_rawDescOnce.Do(func() {
		file_v1_entity_message_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_entity_message_metadata_proto_rawDesc), len(file_v1_entity_message_metadata_proto_rawDesc)))
	})
	return file_v1_entity_message_metadata_proto_rawDescData
}

var file_v1_entity_message_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_entity_message_metadata_proto_goTypes = []any{
	(*MessageMetadata)(nil), // 0: pro.yarns.api.v1.entity.MessageMetadata
}
var file_v1_entity_message_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_entity_message_metadata_proto_init() }
func file_v1_entity_message_metadata_proto_init() {
	if File_v1_entity_message_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_entity_message_metadata_proto_rawDesc), len(file_v1_entity_message_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_entity_message_metadata_proto_goTypes,
		DependencyIndexes: file_v1_entity_message_metadata_proto_depIdxs,
		MessageInfos:      file_v1_entity_message_metadata_proto_msgTypes,
	}.Build()
	File_v1_entity_message_metadata_proto = out.File
	file_v1_entity_message_metadata_proto_goTypes = nil
	file_v1_entity_message_metadata_proto_depIdxs = nil
}
