// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/entity/message_type.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNKNOWN MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT    MessageType = 1
	MessageType_MESSAGE_TYPE_FILE    MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNKNOWN",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_FILE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNKNOWN": 0,
		"MESSAGE_TYPE_TEXT":    1,
		"MESSAGE_TYPE_FILE":    2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_entity_message_type_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_v1_entity_message_type_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_v1_entity_message_type_proto_rawDescGZIP(), []int{0}
}

var File_v1_entity_message_type_proto protoreflect.FileDescriptor

const file_v1_entity_message_type_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/entity/message_type.proto\x12\x17pro.yarns.api.v1.entity\x1a\x1fgoogle/protobuf/timestamp.proto*U\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MESSAGE_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x02B+Z)github.com/yarns-pro/api/pkg/go/v1/entityb\x06proto3"

var (
	file_v1_entity_message_type_proto_rawDescOnce sync.Once
	file_v1_entity_message_type_proto_rawDescData []byte
)

func file_v1_entity_message_type_proto_rawDescGZIP() []byte {
	file_v1_entity_message_type_proto_rawDescOnce.Do(func() {
		file_v1_entity_message_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_entity_message_type_proto_rawDesc), len(file_v1_entity_message_type_proto_rawDesc)))
	})
	return file_v1_entity_message_type_proto_rawDescData
}

var file_v1_entity_message_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_entity_message_type_proto_goTypes = []any{
	(MessageType)(0), // 0: pro.yarns.api.v1.entity.MessageType
}
var file_v1_entity_message_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_entity_message_type_proto_init() }
func file_v1_entity_message_type_proto_init() {
	if File_v1_entity_message_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_entity_message_type_proto_rawDesc), len(file_v1_entity_message_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_entity_message_type_proto_goTypes,
		DependencyIndexes: file_v1_entity_message_type_proto_depIdxs,
		EnumInfos:         file_v1_entity_message_type_proto_enumTypes,
	}.Build()
	File_v1_entity_message_type_proto = out.File
	file_v1_entity_message_type_proto_goTypes = nil
	file_v1_entity_message_type_proto_depIdxs = nil
}
