// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/entity/message.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From              int64                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                int64                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	SentAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	Type              MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=pro.yarns.api.v1.entity.MessageType" json:"type,omitempty"`
	EncryptedMetadata []byte                 `protobuf:"bytes,6,opt,name=encryptedMetadata,proto3" json:"encryptedMetadata,omitempty"`
	EncryptedBody     []byte                 `protobuf:"bytes,7,opt,name=encryptedBody,proto3" json:"encryptedBody,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_v1_entity_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v1_entity_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v1_entity_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *Message) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.EncryptedMetadata
	}
	return nil
}

func (x *Message) GetEncryptedBody() []byte {
	if x != nil {
		return x.EncryptedBody
	}
	return nil
}

var File_v1_entity_message_proto protoreflect.FileDescriptor

const file_v1_entity_message_proto_rawDesc = "" +
	"\n" +
	"\x17v1/entity/message.proto\x12\x17pro.yarns.api.v1.entity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cv1/entity/message_type.proto\"\xff\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x03R\x02to\x122\n" +
	"\x06sentAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x128\n" +
	"\x04type\x18\x05 \x01(\x0e2$.pro.yarns.api.v1.entity.MessageTypeR\x04type\x12,\n" +
	"\x11encryptedMetadata\x18\x06 \x01(\fR\x11encryptedMetadata\x12$\n" +
	"\rencryptedBody\x18\a \x01(\fR\rencryptedBodyB+Z)github.com/yarns-pro/api/pkg/go/v1/entityb\x06proto3"

var (
	file_v1_entity_message_proto_rawDescOnce sync.Once
	file_v1_entity_message_proto_rawDescData []byte
)

func file_v1_entity_message_proto_rawDescGZIP() []byte {
	file_v1_entity_message_proto_rawDescOnce.Do(func() {
		file_v1_entity_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_entity_message_proto_rawDesc), len(file_v1_entity_message_proto_rawDesc)))
	})
	return file_v1_entity_message_proto_rawDescData
}

var file_v1_entity_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_entity_message_proto_goTypes = []any{
	(*Message)(nil),               // 0: pro.yarns.api.v1.entity.Message
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(MessageType)(0),              // 2: pro.yarns.api.v1.entity.MessageType
}
var file_v1_entity_message_proto_depIdxs = []int32{
	1, // 0: pro.yarns.api.v1.entity.Message.sentAt:type_name -> google.protobuf.Timestamp
	2, // 1: pro.yarns.api.v1.entity.Message.type:type_name -> pro.yarns.api.v1.entity.MessageType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_entity_message_proto_init() }
func file_v1_entity_message_proto_init() {
	if File_v1_entity_message_proto != nil {
		return
	}
	file_v1_entity_message_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_entity_message_proto_rawDesc), len(file_v1_entity_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_entity_message_proto_goTypes,
		DependencyIndexes: file_v1_entity_message_proto_depIdxs,
		MessageInfos:      file_v1_entity_message_proto_msgTypes,
	}.Build()
	File_v1_entity_message_proto = out.File
	file_v1_entity_message_proto_goTypes = nil
	file_v1_entity_message_proto_depIdxs = nil
}
