// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/entity/user.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ActiveAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=activeAt,proto3" json:"activeAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_entity_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_entity_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_entity_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetActiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActiveAt
	}
	return nil
}

var File_v1_entity_user_proto protoreflect.FileDescriptor

const file_v1_entity_user_proto_rawDesc = "" +
	"\n" +
	"\x14v1/entity/user.proto\x12\x17pro.yarns.api.v1.entity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tpublicKey\x18\x02 \x01(\fR\tpublicKey\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\bactiveAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bactiveAtB+Z)github.com/yarns-pro/api/pkg/go/v1/entityb\x06proto3"

var (
	file_v1_entity_user_proto_rawDescOnce sync.Once
	file_v1_entity_user_proto_rawDescData []byte
)

func file_v1_entity_user_proto_rawDescGZIP() []byte {
	file_v1_entity_user_proto_rawDescOnce.Do(func() {
		file_v1_entity_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_entity_user_proto_rawDesc), len(file_v1_entity_user_proto_rawDesc)))
	})
	return file_v1_entity_user_proto_rawDescData
}

var file_v1_entity_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_entity_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: pro.yarns.api.v1.entity.User
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_v1_entity_user_proto_depIdxs = []int32{
	1, // 0: pro.yarns.api.v1.entity.User.createdAt:type_name -> google.protobuf.Timestamp
	1, // 1: pro.yarns.api.v1.entity.User.activeAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_entity_user_proto_init() }
func file_v1_entity_user_proto_init() {
	if File_v1_entity_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_entity_user_proto_rawDesc), len(file_v1_entity_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_entity_user_proto_goTypes,
		DependencyIndexes: file_v1_entity_user_proto_depIdxs,
		MessageInfos:      file_v1_entity_user_proto_msgTypes,
	}.Build()
	File_v1_entity_user_proto = out.File
	file_v1_entity_user_proto_goTypes = nil
	file_v1_entity_user_proto_depIdxs = nil
}
