// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/service/service.proto

package service

import (
	entity "github.com/yarns-pro/api/pkg/go/v1/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_v1_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entity.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_v1_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetUser() *entity.User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_v1_service_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entity.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_v1_service_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByIdResponse) GetUser() *entity.User {
	if x != nil {
		return x.User
	}
	return nil
}

type SendMessageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	To                int64                  `protobuf:"varint,1,opt,name=to,proto3" json:"to,omitempty"`
	Type              entity.MessageType     `protobuf:"varint,2,opt,name=type,proto3,enum=pro.yarns.api.v1.entity.MessageType" json:"type,omitempty"`
	EncryptedMetadata []byte                 `protobuf:"bytes,3,opt,name=encryptedMetadata,proto3" json:"encryptedMetadata,omitempty"`
	EncryptedBody     []byte                 `protobuf:"bytes,4,opt,name=encryptedBody,proto3" json:"encryptedBody,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_v1_service_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *SendMessageRequest) GetType() entity.MessageType {
	if x != nil {
		return x.Type
	}
	return entity.MessageType(0)
}

func (x *SendMessageRequest) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.EncryptedMetadata
	}
	return nil
}

func (x *SendMessageRequest) GetEncryptedBody() []byte {
	if x != nil {
		return x.EncryptedBody
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_v1_service_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type CheckMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastMessageId int64                  `protobuf:"varint,1,opt,name=lastMessageId,proto3" json:"lastMessageId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMessagesRequest) Reset() {
	*x = CheckMessagesRequest{}
	mi := &file_v1_service_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMessagesRequest) ProtoMessage() {}

func (x *CheckMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMessagesRequest.ProtoReflect.Descriptor instead.
func (*CheckMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckMessagesRequest) GetLastMessageId() int64 {
	if x != nil {
		return x.LastMessageId
	}
	return 0
}

type CheckMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*entity.Message      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMessagesResponse) Reset() {
	*x = CheckMessagesResponse{}
	mi := &file_v1_service_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMessagesResponse) ProtoMessage() {}

func (x *CheckMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMessagesResponse.ProtoReflect.Descriptor instead.
func (*CheckMessagesResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{7}
}

func (x *CheckMessagesResponse) GetMessages() []*entity.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ConfirmMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []int64                `protobuf:"varint,1,rep,packed,name=messageIds,proto3" json:"messageIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmMessagesRequest) Reset() {
	*x = ConfirmMessagesRequest{}
	mi := &file_v1_service_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmMessagesRequest) ProtoMessage() {}

func (x *ConfirmMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmMessagesRequest.ProtoReflect.Descriptor instead.
func (*ConfirmMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmMessagesRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type ConfirmMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmMessagesResponse) Reset() {
	*x = ConfirmMessagesResponse{}
	mi := &file_v1_service_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmMessagesResponse) ProtoMessage() {}

func (x *ConfirmMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmMessagesResponse.ProtoReflect.Descriptor instead.
func (*ConfirmMessagesResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{9}
}

var File_v1_service_service_proto protoreflect.FileDescriptor

const file_v1_service_service_proto_rawDesc = "" +
	"\n" +
	"\x18v1/service/service.proto\x12\x18pro.yarns.api.v1.service\x1a\x14v1/entity/user.proto\x1a\x17v1/entity/message.proto\x1a\x1cv1/entity/message_type.proto\"3\n" +
	"\x13RegisterUserRequest\x12\x1c\n" +
	"\tpublicKey\x18\x01 \x01(\fR\tpublicKey\"I\n" +
	"\x14RegisterUserResponse\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.pro.yarns.api.v1.entity.UserR\x04user\",\n" +
	"\x12GetUserByIdRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"H\n" +
	"\x13GetUserByIdResponse\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.pro.yarns.api.v1.entity.UserR\x04user\"\xb2\x01\n" +
	"\x12SendMessageRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\x03R\x02to\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.pro.yarns.api.v1.entity.MessageTypeR\x04type\x12,\n" +
	"\x11encryptedMetadata\x18\x03 \x01(\fR\x11encryptedMetadata\x12$\n" +
	"\rencryptedBody\x18\x04 \x01(\fR\rencryptedBody\"3\n" +
	"\x13SendMessageResponse\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\x03R\tmessageId\"<\n" +
	"\x14CheckMessagesRequest\x12$\n" +
	"\rlastMessageId\x18\x01 \x01(\x03R\rlastMessageId\"U\n" +
	"\x15CheckMessagesResponse\x12<\n" +
	"\bmessages\x18\x01 \x03(\v2 .pro.yarns.api.v1.entity.MessageR\bmessages\"8\n" +
	"\x16ConfirmMessagesRequest\x12\x1e\n" +
	"\n" +
	"messageIds\x18\x01 \x03(\x03R\n" +
	"messageIds\"\x19\n" +
	"\x17ConfirmMessagesResponse2\xbd\x04\n" +
	"\n" +
	"YarnsApiV1\x12m\n" +
	"\fRegisterUser\x12-.pro.yarns.api.v1.service.RegisterUserRequest\x1a..pro.yarns.api.v1.service.RegisterUserResponse\x12j\n" +
	"\vGetUserById\x12,.pro.yarns.api.v1.service.GetUserByIdRequest\x1a-.pro.yarns.api.v1.service.GetUserByIdResponse\x12j\n" +
	"\vSendMessage\x12,.pro.yarns.api.v1.service.SendMessageRequest\x1a-.pro.yarns.api.v1.service.SendMessageResponse\x12p\n" +
	"\rCheckMessages\x12..pro.yarns.api.v1.service.CheckMessagesRequest\x1a/.pro.yarns.api.v1.service.CheckMessagesResponse\x12v\n" +
	"\x0fConfirmMessages\x120.pro.yarns.api.v1.service.ConfirmMessagesRequest\x1a1.pro.yarns.api.v1.service.ConfirmMessagesResponseBV\n" +
	"\x18pro.yarns.api.v1.serviceB\fServiceProtoP\x01Z*github.com/yarns-pro/api/pkg/go/v1/serviceb\x06proto3"

var (
	file_v1_service_service_proto_rawDescOnce sync.Once
	file_v1_service_service_proto_rawDescData []byte
)

func file_v1_service_service_proto_rawDescGZIP() []byte {
	file_v1_service_service_proto_rawDescOnce.Do(func() {
		file_v1_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_service_proto_rawDesc), len(file_v1_service_service_proto_rawDesc)))
	})
	return file_v1_service_service_proto_rawDescData
}

var file_v1_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_service_service_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),     // 0: pro.yarns.api.v1.service.RegisterUserRequest
	(*RegisterUserResponse)(nil),    // 1: pro.yarns.api.v1.service.RegisterUserResponse
	(*GetUserByIdRequest)(nil),      // 2: pro.yarns.api.v1.service.GetUserByIdRequest
	(*GetUserByIdResponse)(nil),     // 3: pro.yarns.api.v1.service.GetUserByIdResponse
	(*SendMessageRequest)(nil),      // 4: pro.yarns.api.v1.service.SendMessageRequest
	(*SendMessageResponse)(nil),     // 5: pro.yarns.api.v1.service.SendMessageResponse
	(*CheckMessagesRequest)(nil),    // 6: pro.yarns.api.v1.service.CheckMessagesRequest
	(*CheckMessagesResponse)(nil),   // 7: pro.yarns.api.v1.service.CheckMessagesResponse
	(*ConfirmMessagesRequest)(nil),  // 8: pro.yarns.api.v1.service.ConfirmMessagesRequest
	(*ConfirmMessagesResponse)(nil), // 9: pro.yarns.api.v1.service.ConfirmMessagesResponse
	(*entity.User)(nil),             // 10: pro.yarns.api.v1.entity.User
	(entity.MessageType)(0),         // 11: pro.yarns.api.v1.entity.MessageType
	(*entity.Message)(nil),          // 12: pro.yarns.api.v1.entity.Message
}
var file_v1_service_service_proto_depIdxs = []int32{
	10, // 0: pro.yarns.api.v1.service.RegisterUserResponse.user:type_name -> pro.yarns.api.v1.entity.User
	10, // 1: pro.yarns.api.v1.service.GetUserByIdResponse.user:type_name -> pro.yarns.api.v1.entity.User
	11, // 2: pro.yarns.api.v1.service.SendMessageRequest.type:type_name -> pro.yarns.api.v1.entity.MessageType
	12, // 3: pro.yarns.api.v1.service.CheckMessagesResponse.messages:type_name -> pro.yarns.api.v1.entity.Message
	0,  // 4: pro.yarns.api.v1.service.YarnsApiV1.RegisterUser:input_type -> pro.yarns.api.v1.service.RegisterUserRequest
	2,  // 5: pro.yarns.api.v1.service.YarnsApiV1.GetUserById:input_type -> pro.yarns.api.v1.service.GetUserByIdRequest
	4,  // 6: pro.yarns.api.v1.service.YarnsApiV1.SendMessage:input_type -> pro.yarns.api.v1.service.SendMessageRequest
	6,  // 7: pro.yarns.api.v1.service.YarnsApiV1.CheckMessages:input_type -> pro.yarns.api.v1.service.CheckMessagesRequest
	8,  // 8: pro.yarns.api.v1.service.YarnsApiV1.ConfirmMessages:input_type -> pro.yarns.api.v1.service.ConfirmMessagesRequest
	1,  // 9: pro.yarns.api.v1.service.YarnsApiV1.RegisterUser:output_type -> pro.yarns.api.v1.service.RegisterUserResponse
	3,  // 10: pro.yarns.api.v1.service.YarnsApiV1.GetUserById:output_type -> pro.yarns.api.v1.service.GetUserByIdResponse
	5,  // 11: pro.yarns.api.v1.service.YarnsApiV1.SendMessage:output_type -> pro.yarns.api.v1.service.SendMessageResponse
	7,  // 12: pro.yarns.api.v1.service.YarnsApiV1.CheckMessages:output_type -> pro.yarns.api.v1.service.CheckMessagesResponse
	9,  // 13: pro.yarns.api.v1.service.YarnsApiV1.ConfirmMessages:output_type -> pro.yarns.api.v1.service.ConfirmMessagesResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_service_service_proto_init() }
func file_v1_service_service_proto_init() {
	if File_v1_service_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_service_proto_rawDesc), len(file_v1_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_service_proto_goTypes,
		DependencyIndexes: file_v1_service_service_proto_depIdxs,
		MessageInfos:      file_v1_service_service_proto_msgTypes,
	}.Build()
	File_v1_service_service_proto = out.File
	file_v1_service_service_proto_goTypes = nil
	file_v1_service_service_proto_depIdxs = nil
}
