// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/service/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YarnsApiV1_Register_FullMethodName       = "/pro.yarns.api.v1.service.YarnsApiV1/Register"
	YarnsApiV1_GetUserById_FullMethodName    = "/pro.yarns.api.v1.service.YarnsApiV1/GetUserById"
	YarnsApiV1_SendMessage_FullMethodName    = "/pro.yarns.api.v1.service.YarnsApiV1/SendMessage"
	YarnsApiV1_CheckMessages_FullMethodName  = "/pro.yarns.api.v1.service.YarnsApiV1/CheckMessages"
	YarnsApiV1_GetMessageById_FullMethodName = "/pro.yarns.api.v1.service.YarnsApiV1/GetMessageById"
	YarnsApiV1_ConfirmReceive_FullMethodName = "/pro.yarns.api.v1.service.YarnsApiV1/ConfirmReceive"
)

// YarnsApiV1Client is the client API for YarnsApiV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YarnsApiV1Client interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	CheckMessages(ctx context.Context, in *CheckMessagesRequest, opts ...grpc.CallOption) (*CheckMessagesResponse, error)
	GetMessageById(ctx context.Context, in *GetMessageByIdRequest, opts ...grpc.CallOption) (*GetMessageByIdResponse, error)
	ConfirmReceive(ctx context.Context, in *ConfirmReceiveRequest, opts ...grpc.CallOption) (*ConfirmReceiveResponse, error)
}

type yarnsApiV1Client struct {
	cc grpc.ClientConnInterface
}

func NewYarnsApiV1Client(cc grpc.ClientConnInterface) YarnsApiV1Client {
	return &yarnsApiV1Client{cc}
}

func (c *yarnsApiV1Client) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, YarnsApiV1_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yarnsApiV1Client) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByIdResponse)
	err := c.cc.Invoke(ctx, YarnsApiV1_GetUserById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yarnsApiV1Client) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, YarnsApiV1_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yarnsApiV1Client) CheckMessages(ctx context.Context, in *CheckMessagesRequest, opts ...grpc.CallOption) (*CheckMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMessagesResponse)
	err := c.cc.Invoke(ctx, YarnsApiV1_CheckMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yarnsApiV1Client) GetMessageById(ctx context.Context, in *GetMessageByIdRequest, opts ...grpc.CallOption) (*GetMessageByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageByIdResponse)
	err := c.cc.Invoke(ctx, YarnsApiV1_GetMessageById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yarnsApiV1Client) ConfirmReceive(ctx context.Context, in *ConfirmReceiveRequest, opts ...grpc.CallOption) (*ConfirmReceiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmReceiveResponse)
	err := c.cc.Invoke(ctx, YarnsApiV1_ConfirmReceive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YarnsApiV1Server is the server API for YarnsApiV1 service.
// All implementations must embed UnimplementedYarnsApiV1Server
// for forward compatibility.
type YarnsApiV1Server interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetUserById(context.Context, *GetUserByIdRequest) (*GetUserByIdResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	CheckMessages(context.Context, *CheckMessagesRequest) (*CheckMessagesResponse, error)
	GetMessageById(context.Context, *GetMessageByIdRequest) (*GetMessageByIdResponse, error)
	ConfirmReceive(context.Context, *ConfirmReceiveRequest) (*ConfirmReceiveResponse, error)
	mustEmbedUnimplementedYarnsApiV1Server()
}

// UnimplementedYarnsApiV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYarnsApiV1Server struct{}

func (UnimplementedYarnsApiV1Server) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedYarnsApiV1Server) GetUserById(context.Context, *GetUserByIdRequest) (*GetUserByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (UnimplementedYarnsApiV1Server) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedYarnsApiV1Server) CheckMessages(context.Context, *CheckMessagesRequest) (*CheckMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckMessages not implemented")
}
func (UnimplementedYarnsApiV1Server) GetMessageById(context.Context, *GetMessageByIdRequest) (*GetMessageByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageById not implemented")
}
func (UnimplementedYarnsApiV1Server) ConfirmReceive(context.Context, *ConfirmReceiveRequest) (*ConfirmReceiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmReceive not implemented")
}
func (UnimplementedYarnsApiV1Server) mustEmbedUnimplementedYarnsApiV1Server() {}
func (UnimplementedYarnsApiV1Server) testEmbeddedByValue()                    {}

// UnsafeYarnsApiV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YarnsApiV1Server will
// result in compilation errors.
type UnsafeYarnsApiV1Server interface {
	mustEmbedUnimplementedYarnsApiV1Server()
}

func RegisterYarnsApiV1Server(s grpc.ServiceRegistrar, srv YarnsApiV1Server) {
	// If the following call pancis, it indicates UnimplementedYarnsApiV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YarnsApiV1_ServiceDesc, srv)
}

func _YarnsApiV1_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YarnsApiV1Server).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YarnsApiV1_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YarnsApiV1Server).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YarnsApiV1_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YarnsApiV1Server).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YarnsApiV1_GetUserById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YarnsApiV1Server).GetUserById(ctx, req.(*GetUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YarnsApiV1_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YarnsApiV1Server).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YarnsApiV1_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YarnsApiV1Server).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YarnsApiV1_CheckMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YarnsApiV1Server).CheckMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YarnsApiV1_CheckMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YarnsApiV1Server).CheckMessages(ctx, req.(*CheckMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YarnsApiV1_GetMessageById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YarnsApiV1Server).GetMessageById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YarnsApiV1_GetMessageById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YarnsApiV1Server).GetMessageById(ctx, req.(*GetMessageByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YarnsApiV1_ConfirmReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YarnsApiV1Server).ConfirmReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YarnsApiV1_ConfirmReceive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YarnsApiV1Server).ConfirmReceive(ctx, req.(*ConfirmReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YarnsApiV1_ServiceDesc is the grpc.ServiceDesc for YarnsApiV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YarnsApiV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pro.yarns.api.v1.service.YarnsApiV1",
	HandlerType: (*YarnsApiV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _YarnsApiV1_Register_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _YarnsApiV1_GetUserById_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _YarnsApiV1_SendMessage_Handler,
		},
		{
			MethodName: "CheckMessages",
			Handler:    _YarnsApiV1_CheckMessages_Handler,
		},
		{
			MethodName: "GetMessageById",
			Handler:    _YarnsApiV1_GetMessageById_Handler,
		},
		{
			MethodName: "ConfirmReceive",
			Handler:    _YarnsApiV1_ConfirmReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/service/service.proto",
}
