// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/service/service.proto

package service

import (
	entity "github.com/yarns-pro/api/pkg/go/v1/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_v1_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entity.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_v1_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUser() *entity.User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRequest) Reset() {
	*x = GetByIdRequest{}
	mi := &file_v1_service_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRequest) ProtoMessage() {}

func (x *GetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entity.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdResponse) Reset() {
	*x = GetByIdResponse{}
	mi := &file_v1_service_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdResponse) ProtoMessage() {}

func (x *GetByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdResponse.ProtoReflect.Descriptor instead.
func (*GetByIdResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetByIdResponse) GetUser() *entity.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_v1_service_service_proto protoreflect.FileDescriptor

const file_v1_service_service_proto_rawDesc = "" +
	"\n" +
	"\x18v1/service/service.proto\x12#ru.kamenetskii.yarns.api.v1.service\x1a\x14v1/entity/user.proto\"/\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\tpublicKey\x18\x01 \x01(\fR\tpublicKey\"P\n" +
	"\x10RegisterResponse\x12<\n" +
	"\x04user\x18\x01 \x01(\v2(.ru.kamenetskii.yarns.api.v1.entity.UserR\x04user\"(\n" +
	"\x0eGetByIdRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"O\n" +
	"\x0fGetByIdResponse\x12<\n" +
	"\x04user\x18\x01 \x01(\v2(.ru.kamenetskii.yarns.api.v1.entity.UserR\x04user2\xfb\x01\n" +
	"\n" +
	"YarnsApiV1\x12w\n" +
	"\bRegister\x124.ru.kamenetskii.yarns.api.v1.service.RegisterRequest\x1a5.ru.kamenetskii.yarns.api.v1.service.RegisterResponse\x12t\n" +
	"\aGetById\x123.ru.kamenetskii.yarns.api.v1.service.GetByIdRequest\x1a4.ru.kamenetskii.yarns.api.v1.service.GetByIdResponseBa\n" +
	"#ru.kamenetskii.yarns.api.v1.serviceB\fServiceProtoP\x01Z*github.com/yarns-pro/api/pkg/go/v1/serviceb\x06proto3"

var (
	file_v1_service_service_proto_rawDescOnce sync.Once
	file_v1_service_service_proto_rawDescData []byte
)

func file_v1_service_service_proto_rawDescGZIP() []byte {
	file_v1_service_service_proto_rawDescOnce.Do(func() {
		file_v1_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_service_proto_rawDesc), len(file_v1_service_service_proto_rawDesc)))
	})
	return file_v1_service_service_proto_rawDescData
}

var file_v1_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_service_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: ru.kamenetskii.yarns.api.v1.service.RegisterRequest
	(*RegisterResponse)(nil), // 1: ru.kamenetskii.yarns.api.v1.service.RegisterResponse
	(*GetByIdRequest)(nil),   // 2: ru.kamenetskii.yarns.api.v1.service.GetByIdRequest
	(*GetByIdResponse)(nil),  // 3: ru.kamenetskii.yarns.api.v1.service.GetByIdResponse
	(*entity.User)(nil),      // 4: ru.kamenetskii.yarns.api.v1.entity.User
}
var file_v1_service_service_proto_depIdxs = []int32{
	4, // 0: ru.kamenetskii.yarns.api.v1.service.RegisterResponse.user:type_name -> ru.kamenetskii.yarns.api.v1.entity.User
	4, // 1: ru.kamenetskii.yarns.api.v1.service.GetByIdResponse.user:type_name -> ru.kamenetskii.yarns.api.v1.entity.User
	0, // 2: ru.kamenetskii.yarns.api.v1.service.YarnsApiV1.Register:input_type -> ru.kamenetskii.yarns.api.v1.service.RegisterRequest
	2, // 3: ru.kamenetskii.yarns.api.v1.service.YarnsApiV1.GetById:input_type -> ru.kamenetskii.yarns.api.v1.service.GetByIdRequest
	1, // 4: ru.kamenetskii.yarns.api.v1.service.YarnsApiV1.Register:output_type -> ru.kamenetskii.yarns.api.v1.service.RegisterResponse
	3, // 5: ru.kamenetskii.yarns.api.v1.service.YarnsApiV1.GetById:output_type -> ru.kamenetskii.yarns.api.v1.service.GetByIdResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_service_service_proto_init() }
func file_v1_service_service_proto_init() {
	if File_v1_service_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_service_proto_rawDesc), len(file_v1_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_service_proto_goTypes,
		DependencyIndexes: file_v1_service_service_proto_depIdxs,
		MessageInfos:      file_v1_service_service_proto_msgTypes,
	}.Build()
	File_v1_service_service_proto = out.File
	file_v1_service_service_proto_goTypes = nil
	file_v1_service_service_proto_depIdxs = nil
}
