// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/entity/message_metadata.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.entity;

@kotlin.jvm.JvmName("-initializemessageMetadata")
public inline fun messageMetadata(block: pro.yarns.api.v1.entity.MessageMetadataKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.entity.MessageMetadataOuterClass.MessageMetadata =
  pro.yarns.api.v1.entity.MessageMetadataKt.Dsl._create(pro.yarns.api.v1.entity.MessageMetadataOuterClass.MessageMetadata.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.entity.MessageMetadata`
 */
public object MessageMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.entity.MessageMetadataOuterClass.MessageMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.entity.MessageMetadataOuterClass.MessageMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.entity.MessageMetadataOuterClass.MessageMetadata = _builder.build()

    /**
     * `string mimeType = 1 [json_name = "mimeType"];`
     */
    public var mimeType: kotlin.String
      @kotlin.jvm.JvmName("getMimeType")
        get() = _builder.mimeType
      @kotlin.jvm.JvmName("setMimeType")
        set(value) {
        _builder.mimeType = value
      }
    /**
     * `string mimeType = 1 [json_name = "mimeType"];`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }

    /**
     * `string filename = 2 [json_name = "filename"];`
     */
    public var filename: kotlin.String
      @kotlin.jvm.JvmName("getFilename")
        get() = _builder.filename
      @kotlin.jvm.JvmName("setFilename")
        set(value) {
        _builder.filename = value
      }
    /**
     * `string filename = 2 [json_name = "filename"];`
     */
    public fun clearFilename() {
      _builder.clearFilename()
    }

    /**
     * `int64 filesize = 3 [json_name = "filesize"];`
     */
    public var filesize: kotlin.Long
      @kotlin.jvm.JvmName("getFilesize")
        get() = _builder.filesize
      @kotlin.jvm.JvmName("setFilesize")
        set(value) {
        _builder.filesize = value
      }
    /**
     * `int64 filesize = 3 [json_name = "filesize"];`
     */
    public fun clearFilesize() {
      _builder.clearFilesize()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.entity.MessageMetadataOuterClass.MessageMetadata.copy(block: `pro.yarns.api.v1.entity`.MessageMetadataKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.entity.MessageMetadataOuterClass.MessageMetadata =
  `pro.yarns.api.v1.entity`.MessageMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

