// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/entity/message.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.entity;

@com.google.protobuf.Generated
public final class MessageOuterClass {
  private MessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pro.yarns.api.v1.entity.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 from = 2 [json_name = "from"];</code>
     * @return The from.
     */
    long getFrom();

    /**
     * <code>int64 to = 3 [json_name = "to"];</code>
     * @return The to.
     */
    long getTo();

    /**
     * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
     * @return Whether the sentAt field is set.
     */
    boolean hasSentAt();
    /**
     * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
     * @return The sentAt.
     */
    com.google.protobuf.Timestamp getSentAt();
    /**
     * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
     */
    com.google.protobuf.TimestampOrBuilder getSentAtOrBuilder();

    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
     * @return The type.
     */
    pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType getType();

    /**
     * <code>bytes encryptedMetadata = 6 [json_name = "encryptedMetadata"];</code>
     * @return The encryptedMetadata.
     */
    com.google.protobuf.ByteString getEncryptedMetadata();

    /**
     * <code>bytes encryptedBody = 7 [json_name = "encryptedBody"];</code>
     * @return The encryptedBody.
     */
    com.google.protobuf.ByteString getEncryptedBody();
  }
  /**
   * Protobuf type {@code pro.yarns.api.v1.entity.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pro.yarns.api.v1.entity.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      encryptedMetadata_ = com.google.protobuf.ByteString.EMPTY;
      encryptedBody_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pro.yarns.api.v1.entity.MessageOuterClass.internal_static_pro_yarns_api_v1_entity_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pro.yarns.api.v1.entity.MessageOuterClass.internal_static_pro_yarns_api_v1_entity_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pro.yarns.api.v1.entity.MessageOuterClass.Message.class, pro.yarns.api.v1.entity.MessageOuterClass.Message.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private long from_ = 0L;
    /**
     * <code>int64 from = 2 [json_name = "from"];</code>
     * @return The from.
     */
    @java.lang.Override
    public long getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 3;
    private long to_ = 0L;
    /**
     * <code>int64 to = 3 [json_name = "to"];</code>
     * @return The to.
     */
    @java.lang.Override
    public long getTo() {
      return to_;
    }

    public static final int SENTAT_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp sentAt_;
    /**
     * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
     * @return Whether the sentAt field is set.
     */
    @java.lang.Override
    public boolean hasSentAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
     * @return The sentAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getSentAt() {
      return sentAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sentAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getSentAtOrBuilder() {
      return sentAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sentAt_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_ = 0;
    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override public pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType getType() {
      pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType result = pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.forNumber(type_);
      return result == null ? pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.UNRECOGNIZED : result;
    }

    public static final int ENCRYPTEDMETADATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString encryptedMetadata_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encryptedMetadata = 6 [json_name = "encryptedMetadata"];</code>
     * @return The encryptedMetadata.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedMetadata() {
      return encryptedMetadata_;
    }

    public static final int ENCRYPTEDBODY_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString encryptedBody_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encryptedBody = 7 [json_name = "encryptedBody"];</code>
     * @return The encryptedBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedBody() {
      return encryptedBody_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (from_ != 0L) {
        output.writeInt64(2, from_);
      }
      if (to_ != 0L) {
        output.writeInt64(3, to_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getSentAt());
      }
      if (type_ != pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.MESSAGE_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(5, type_);
      }
      if (!encryptedMetadata_.isEmpty()) {
        output.writeBytes(6, encryptedMetadata_);
      }
      if (!encryptedBody_.isEmpty()) {
        output.writeBytes(7, encryptedBody_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (from_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, from_);
      }
      if (to_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, to_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSentAt());
      }
      if (type_ != pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.MESSAGE_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      if (!encryptedMetadata_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, encryptedMetadata_);
      }
      if (!encryptedBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, encryptedBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pro.yarns.api.v1.entity.MessageOuterClass.Message)) {
        return super.equals(obj);
      }
      pro.yarns.api.v1.entity.MessageOuterClass.Message other = (pro.yarns.api.v1.entity.MessageOuterClass.Message) obj;

      if (getId()
          != other.getId()) return false;
      if (getFrom()
          != other.getFrom()) return false;
      if (getTo()
          != other.getTo()) return false;
      if (hasSentAt() != other.hasSentAt()) return false;
      if (hasSentAt()) {
        if (!getSentAt()
            .equals(other.getSentAt())) return false;
      }
      if (type_ != other.type_) return false;
      if (!getEncryptedMetadata()
          .equals(other.getEncryptedMetadata())) return false;
      if (!getEncryptedBody()
          .equals(other.getEncryptedBody())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrom());
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTo());
      if (hasSentAt()) {
        hash = (37 * hash) + SENTAT_FIELD_NUMBER;
        hash = (53 * hash) + getSentAt().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ENCRYPTEDMETADATA_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedMetadata().hashCode();
      hash = (37 * hash) + ENCRYPTEDBODY_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedBody().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pro.yarns.api.v1.entity.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pro.yarns.api.v1.entity.MessageOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pro.yarns.api.v1.entity.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pro.yarns.api.v1.entity.Message)
        pro.yarns.api.v1.entity.MessageOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pro.yarns.api.v1.entity.MessageOuterClass.internal_static_pro_yarns_api_v1_entity_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pro.yarns.api.v1.entity.MessageOuterClass.internal_static_pro_yarns_api_v1_entity_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pro.yarns.api.v1.entity.MessageOuterClass.Message.class, pro.yarns.api.v1.entity.MessageOuterClass.Message.Builder.class);
      }

      // Construct using pro.yarns.api.v1.entity.MessageOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetSentAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        from_ = 0L;
        to_ = 0L;
        sentAt_ = null;
        if (sentAtBuilder_ != null) {
          sentAtBuilder_.dispose();
          sentAtBuilder_ = null;
        }
        type_ = 0;
        encryptedMetadata_ = com.google.protobuf.ByteString.EMPTY;
        encryptedBody_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pro.yarns.api.v1.entity.MessageOuterClass.internal_static_pro_yarns_api_v1_entity_Message_descriptor;
      }

      @java.lang.Override
      public pro.yarns.api.v1.entity.MessageOuterClass.Message getDefaultInstanceForType() {
        return pro.yarns.api.v1.entity.MessageOuterClass.Message.getDefaultInstance();
      }

      @java.lang.Override
      public pro.yarns.api.v1.entity.MessageOuterClass.Message build() {
        pro.yarns.api.v1.entity.MessageOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pro.yarns.api.v1.entity.MessageOuterClass.Message buildPartial() {
        pro.yarns.api.v1.entity.MessageOuterClass.Message result = new pro.yarns.api.v1.entity.MessageOuterClass.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pro.yarns.api.v1.entity.MessageOuterClass.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.from_ = from_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.to_ = to_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sentAt_ = sentAtBuilder_ == null
              ? sentAt_
              : sentAtBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.encryptedMetadata_ = encryptedMetadata_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.encryptedBody_ = encryptedBody_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pro.yarns.api.v1.entity.MessageOuterClass.Message) {
          return mergeFrom((pro.yarns.api.v1.entity.MessageOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pro.yarns.api.v1.entity.MessageOuterClass.Message other) {
        if (other == pro.yarns.api.v1.entity.MessageOuterClass.Message.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getFrom() != 0L) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != 0L) {
          setTo(other.getTo());
        }
        if (other.hasSentAt()) {
          mergeSentAt(other.getSentAt());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getEncryptedMetadata().isEmpty()) {
          setEncryptedMetadata(other.getEncryptedMetadata());
        }
        if (!other.getEncryptedBody().isEmpty()) {
          setEncryptedBody(other.getEncryptedBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                from_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                to_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                input.readMessage(
                    internalGetSentAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                encryptedMetadata_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                encryptedBody_ = input.readBytes();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long from_ ;
      /**
       * <code>int64 from = 2 [json_name = "from"];</code>
       * @return The from.
       */
      @java.lang.Override
      public long getFrom() {
        return from_;
      }
      /**
       * <code>int64 from = 2 [json_name = "from"];</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(long value) {

        from_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 from = 2 [json_name = "from"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = 0L;
        onChanged();
        return this;
      }

      private long to_ ;
      /**
       * <code>int64 to = 3 [json_name = "to"];</code>
       * @return The to.
       */
      @java.lang.Override
      public long getTo() {
        return to_;
      }
      /**
       * <code>int64 to = 3 [json_name = "to"];</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(long value) {

        to_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 to = 3 [json_name = "to"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        to_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp sentAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sentAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       * @return Whether the sentAt field is set.
       */
      public boolean hasSentAt() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       * @return The sentAt.
       */
      public com.google.protobuf.Timestamp getSentAt() {
        if (sentAtBuilder_ == null) {
          return sentAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sentAt_;
        } else {
          return sentAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       */
      public Builder setSentAt(com.google.protobuf.Timestamp value) {
        if (sentAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sentAt_ = value;
        } else {
          sentAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       */
      public Builder setSentAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sentAtBuilder_ == null) {
          sentAt_ = builderForValue.build();
        } else {
          sentAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       */
      public Builder mergeSentAt(com.google.protobuf.Timestamp value) {
        if (sentAtBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            sentAt_ != null &&
            sentAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getSentAtBuilder().mergeFrom(value);
          } else {
            sentAt_ = value;
          }
        } else {
          sentAtBuilder_.mergeFrom(value);
        }
        if (sentAt_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       */
      public Builder clearSentAt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sentAt_ = null;
        if (sentAtBuilder_ != null) {
          sentAtBuilder_.dispose();
          sentAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       */
      public com.google.protobuf.Timestamp.Builder getSentAtBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return internalGetSentAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSentAtOrBuilder() {
        if (sentAtBuilder_ != null) {
          return sentAtBuilder_.getMessageOrBuilder();
        } else {
          return sentAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sentAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sentAt = 4 [json_name = "sentAt"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          internalGetSentAtFieldBuilder() {
        if (sentAtBuilder_ == null) {
          sentAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSentAt(),
                  getParentForChildren(),
                  isClean());
          sentAt_ = null;
        }
        return sentAtBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
       * @return The type.
       */
      @java.lang.Override
      public pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType getType() {
        pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType result = pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.forNumber(type_);
        return result == null ? pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000010;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.pro.yarns.api.v1.entity.MessageType type = 5 [json_name = "type"];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptedMetadata_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encryptedMetadata = 6 [json_name = "encryptedMetadata"];</code>
       * @return The encryptedMetadata.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncryptedMetadata() {
        return encryptedMetadata_;
      }
      /**
       * <code>bytes encryptedMetadata = 6 [json_name = "encryptedMetadata"];</code>
       * @param value The encryptedMetadata to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedMetadata(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        encryptedMetadata_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encryptedMetadata = 6 [json_name = "encryptedMetadata"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedMetadata() {
        bitField0_ = (bitField0_ & ~0x00000020);
        encryptedMetadata_ = getDefaultInstance().getEncryptedMetadata();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptedBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encryptedBody = 7 [json_name = "encryptedBody"];</code>
       * @return The encryptedBody.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncryptedBody() {
        return encryptedBody_;
      }
      /**
       * <code>bytes encryptedBody = 7 [json_name = "encryptedBody"];</code>
       * @param value The encryptedBody to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedBody(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        encryptedBody_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encryptedBody = 7 [json_name = "encryptedBody"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedBody() {
        bitField0_ = (bitField0_ & ~0x00000040);
        encryptedBody_ = getDefaultInstance().getEncryptedBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pro.yarns.api.v1.entity.Message)
    }

    // @@protoc_insertion_point(class_scope:pro.yarns.api.v1.entity.Message)
    private static final pro.yarns.api.v1.entity.MessageOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pro.yarns.api.v1.entity.MessageOuterClass.Message();
    }

    public static pro.yarns.api.v1.entity.MessageOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pro.yarns.api.v1.entity.MessageOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_entity_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_entity_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027v1/entity/message.proto\022\027pro.yarns.api" +
      ".v1.entity\032\037google/protobuf/timestamp.pr" +
      "oto\032\034v1/entity/message_type.proto\"\377\001\n\007Me" +
      "ssage\022\016\n\002id\030\001 \001(\003R\002id\022\022\n\004from\030\002 \001(\003R\004fro" +
      "m\022\016\n\002to\030\003 \001(\003R\002to\0222\n\006sentAt\030\004 \001(\0132\032.goog" +
      "le.protobuf.TimestampR\006sentAt\0228\n\004type\030\005 " +
      "\001(\0162$.pro.yarns.api.v1.entity.MessageTyp" +
      "eR\004type\022,\n\021encryptedMetadata\030\006 \001(\014R\021encr" +
      "yptedMetadata\022$\n\rencryptedBody\030\007 \001(\014R\ren" +
      "cryptedBodyB+Z)github.com/yarns-pro/api/" +
      "pkg/go/v1/entityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          pro.yarns.api.v1.entity.MessageTypeOuterClass.getDescriptor(),
        });
    internal_static_pro_yarns_api_v1_entity_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pro_yarns_api_v1_entity_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_entity_Message_descriptor,
        new java.lang.String[] { "Id", "From", "To", "SentAt", "Type", "EncryptedMetadata", "EncryptedBody", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    pro.yarns.api.v1.entity.MessageTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
