// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/entity/user.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.entity;

@com.google.protobuf.Generated
public final class UserOuterClass {
  private UserOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      UserOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pro.yarns.api.v1.entity.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>bytes publicKey = 2 [json_name = "publicKey"];</code>
     * @return The publicKey.
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
     * @return Whether the activeAt field is set.
     */
    boolean hasActiveAt();
    /**
     * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
     * @return The activeAt.
     */
    com.google.protobuf.Timestamp getActiveAt();
    /**
     * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
     */
    com.google.protobuf.TimestampOrBuilder getActiveAtOrBuilder();
  }
  /**
   * Protobuf type {@code pro.yarns.api.v1.entity.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pro.yarns.api.v1.entity.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        User.class.getName());
    }
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private User() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pro.yarns.api.v1.entity.UserOuterClass.internal_static_pro_yarns_api_v1_entity_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pro.yarns.api.v1.entity.UserOuterClass.internal_static_pro_yarns_api_v1_entity_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pro.yarns.api.v1.entity.UserOuterClass.User.class, pro.yarns.api.v1.entity.UserOuterClass.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes publicKey = 2 [json_name = "publicKey"];</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int CREATEDAT_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }

    public static final int ACTIVEAT_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp activeAt_;
    /**
     * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
     * @return Whether the activeAt field is set.
     */
    @java.lang.Override
    public boolean hasActiveAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
     * @return The activeAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getActiveAt() {
      return activeAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : activeAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getActiveAtOrBuilder() {
      return activeAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : activeAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!publicKey_.isEmpty()) {
        output.writeBytes(2, publicKey_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(4, getActiveAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, publicKey_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getActiveAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pro.yarns.api.v1.entity.UserOuterClass.User)) {
        return super.equals(obj);
      }
      pro.yarns.api.v1.entity.UserOuterClass.User other = (pro.yarns.api.v1.entity.UserOuterClass.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getPublicKey()
          .equals(other.getPublicKey())) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (hasActiveAt() != other.hasActiveAt()) return false;
      if (hasActiveAt()) {
        if (!getActiveAt()
            .equals(other.getActiveAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      if (hasActiveAt()) {
        hash = (37 * hash) + ACTIVEAT_FIELD_NUMBER;
        hash = (53 * hash) + getActiveAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pro.yarns.api.v1.entity.UserOuterClass.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pro.yarns.api.v1.entity.UserOuterClass.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pro.yarns.api.v1.entity.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pro.yarns.api.v1.entity.UserOuterClass.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pro.yarns.api.v1.entity.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pro.yarns.api.v1.entity.User)
        pro.yarns.api.v1.entity.UserOuterClass.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pro.yarns.api.v1.entity.UserOuterClass.internal_static_pro_yarns_api_v1_entity_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pro.yarns.api.v1.entity.UserOuterClass.internal_static_pro_yarns_api_v1_entity_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pro.yarns.api.v1.entity.UserOuterClass.User.class, pro.yarns.api.v1.entity.UserOuterClass.User.Builder.class);
      }

      // Construct using pro.yarns.api.v1.entity.UserOuterClass.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetCreatedAtFieldBuilder();
          internalGetActiveAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        activeAt_ = null;
        if (activeAtBuilder_ != null) {
          activeAtBuilder_.dispose();
          activeAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pro.yarns.api.v1.entity.UserOuterClass.internal_static_pro_yarns_api_v1_entity_User_descriptor;
      }

      @java.lang.Override
      public pro.yarns.api.v1.entity.UserOuterClass.User getDefaultInstanceForType() {
        return pro.yarns.api.v1.entity.UserOuterClass.User.getDefaultInstance();
      }

      @java.lang.Override
      public pro.yarns.api.v1.entity.UserOuterClass.User build() {
        pro.yarns.api.v1.entity.UserOuterClass.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pro.yarns.api.v1.entity.UserOuterClass.User buildPartial() {
        pro.yarns.api.v1.entity.UserOuterClass.User result = new pro.yarns.api.v1.entity.UserOuterClass.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pro.yarns.api.v1.entity.UserOuterClass.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.publicKey_ = publicKey_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.createdAt_ = createdAtBuilder_ == null
              ? createdAt_
              : createdAtBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.activeAt_ = activeAtBuilder_ == null
              ? activeAt_
              : activeAtBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pro.yarns.api.v1.entity.UserOuterClass.User) {
          return mergeFrom((pro.yarns.api.v1.entity.UserOuterClass.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pro.yarns.api.v1.entity.UserOuterClass.User other) {
        if (other == pro.yarns.api.v1.entity.UserOuterClass.User.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getPublicKey().isEmpty()) {
          setPublicKey(other.getPublicKey());
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        if (other.hasActiveAt()) {
          mergeActiveAt(other.getActiveAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                publicKey_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    internalGetCreatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    internalGetActiveAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes publicKey = 2 [json_name = "publicKey"];</code>
       * @return The publicKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes publicKey = 2 [json_name = "publicKey"];</code>
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        publicKey_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes publicKey = 2 [json_name = "publicKey"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createdAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       * @return The createdAt.
       */
      public com.google.protobuf.Timestamp getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
        } else {
          createdAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            createdAt_ != null &&
            createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreatedAtBuilder().mergeFrom(value);
          } else {
            createdAt_ = value;
          }
        } else {
          createdAtBuilder_.mergeFrom(value);
        }
        if (createdAt_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return internalGetCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          internalGetCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      private com.google.protobuf.Timestamp activeAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> activeAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       * @return Whether the activeAt field is set.
       */
      public boolean hasActiveAt() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       * @return The activeAt.
       */
      public com.google.protobuf.Timestamp getActiveAt() {
        if (activeAtBuilder_ == null) {
          return activeAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : activeAt_;
        } else {
          return activeAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       */
      public Builder setActiveAt(com.google.protobuf.Timestamp value) {
        if (activeAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          activeAt_ = value;
        } else {
          activeAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       */
      public Builder setActiveAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (activeAtBuilder_ == null) {
          activeAt_ = builderForValue.build();
        } else {
          activeAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       */
      public Builder mergeActiveAt(com.google.protobuf.Timestamp value) {
        if (activeAtBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            activeAt_ != null &&
            activeAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getActiveAtBuilder().mergeFrom(value);
          } else {
            activeAt_ = value;
          }
        } else {
          activeAtBuilder_.mergeFrom(value);
        }
        if (activeAt_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       */
      public Builder clearActiveAt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        activeAt_ = null;
        if (activeAtBuilder_ != null) {
          activeAtBuilder_.dispose();
          activeAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       */
      public com.google.protobuf.Timestamp.Builder getActiveAtBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return internalGetActiveAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getActiveAtOrBuilder() {
        if (activeAtBuilder_ != null) {
          return activeAtBuilder_.getMessageOrBuilder();
        } else {
          return activeAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : activeAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          internalGetActiveAtFieldBuilder() {
        if (activeAtBuilder_ == null) {
          activeAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getActiveAt(),
                  getParentForChildren(),
                  isClean());
          activeAt_ = null;
        }
        return activeAtBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pro.yarns.api.v1.entity.User)
    }

    // @@protoc_insertion_point(class_scope:pro.yarns.api.v1.entity.User)
    private static final pro.yarns.api.v1.entity.UserOuterClass.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pro.yarns.api.v1.entity.UserOuterClass.User();
    }

    public static pro.yarns.api.v1.entity.UserOuterClass.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pro.yarns.api.v1.entity.UserOuterClass.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_entity_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_entity_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024v1/entity/user.proto\022\027pro.yarns.api.v1" +
      ".entity\032\037google/protobuf/timestamp.proto" +
      "\"\246\001\n\004User\022\016\n\002id\030\001 \001(\003R\002id\022\034\n\tpublicKey\030\002" +
      " \001(\014R\tpublicKey\0228\n\tcreatedAt\030\003 \001(\0132\032.goo" +
      "gle.protobuf.TimestampR\tcreatedAt\0226\n\010act" +
      "iveAt\030\004 \001(\0132\032.google.protobuf.TimestampR" +
      "\010activeAtB+Z)github.com/yarns-pro/api/pk" +
      "g/go/v1/entityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_pro_yarns_api_v1_entity_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pro_yarns_api_v1_entity_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_entity_User_descriptor,
        new java.lang.String[] { "Id", "PublicKey", "CreatedAt", "ActiveAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
