// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/entity/user.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.entity;

@kotlin.jvm.JvmName("-initializeuser")
public inline fun user(block: pro.yarns.api.v1.entity.UserKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.entity.UserOuterClass.User =
  pro.yarns.api.v1.entity.UserKt.Dsl._create(pro.yarns.api.v1.entity.UserOuterClass.User.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.entity.User`
 */
public object UserKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.entity.UserOuterClass.User.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.entity.UserOuterClass.User.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.entity.UserOuterClass.User = _builder.build()

    /**
     * `int64 id = 1 [json_name = "id"];`
     */
    public var id: kotlin.Long
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `int64 id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `bytes publicKey = 2 [json_name = "publicKey"];`
     */
    public var publicKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPublicKey")
        get() = _builder.publicKey
      @kotlin.jvm.JvmName("setPublicKey")
        set(value) {
        _builder.publicKey = value
      }
    /**
     * `bytes publicKey = 2 [json_name = "publicKey"];`
     */
    public fun clearPublicKey() {
      _builder.clearPublicKey()
    }

    /**
     * `.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];`
     */
    public var createdAt: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * `.google.protobuf.Timestamp createdAt = 3 [json_name = "createdAt"];`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    public val UserKt.Dsl.createdAtOrNull: com.google.protobuf.Timestamp?
      get() = _builder.createdAtOrNull

    /**
     * `.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];`
     */
    public var activeAt: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getActiveAt")
        get() = _builder.activeAt
      @kotlin.jvm.JvmName("setActiveAt")
        set(value) {
        _builder.activeAt = value
      }
    /**
     * `.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];`
     */
    public fun clearActiveAt() {
      _builder.clearActiveAt()
    }
    /**
     * `.google.protobuf.Timestamp activeAt = 4 [json_name = "activeAt"];`
     * @return Whether the activeAt field is set.
     */
    public fun hasActiveAt(): kotlin.Boolean {
      return _builder.hasActiveAt()
    }

    public val UserKt.Dsl.activeAtOrNull: com.google.protobuf.Timestamp?
      get() = _builder.activeAtOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.entity.UserOuterClass.User.copy(block: `pro.yarns.api.v1.entity`.UserKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.entity.UserOuterClass.User =
  `pro.yarns.api.v1.entity`.UserKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val pro.yarns.api.v1.entity.UserOuterClass.UserOrBuilder.createdAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

public val pro.yarns.api.v1.entity.UserOuterClass.UserOrBuilder.activeAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasActiveAt()) getActiveAt() else null

