// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.service;

/**
 * Protobuf type {@code pro.yarns.api.v1.service.CheckMessagesRequest}
 */
@com.google.protobuf.Generated
public final class CheckMessagesRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:pro.yarns.api.v1.service.CheckMessagesRequest)
    CheckMessagesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      CheckMessagesRequest.class.getName());
  }
  // Use CheckMessagesRequest.newBuilder() to construct.
  private CheckMessagesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CheckMessagesRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pro.yarns.api.v1.service.CheckMessagesRequest.class, pro.yarns.api.v1.service.CheckMessagesRequest.Builder.class);
  }

  public static final int LASTMESSAGEID_FIELD_NUMBER = 1;
  private long lastMessageId_ = 0L;
  /**
   * <code>int64 lastMessageId = 1 [json_name = "lastMessageId"];</code>
   * @return The lastMessageId.
   */
  @java.lang.Override
  public long getLastMessageId() {
    return lastMessageId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lastMessageId_ != 0L) {
      output.writeInt64(1, lastMessageId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lastMessageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, lastMessageId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pro.yarns.api.v1.service.CheckMessagesRequest)) {
      return super.equals(obj);
    }
    pro.yarns.api.v1.service.CheckMessagesRequest other = (pro.yarns.api.v1.service.CheckMessagesRequest) obj;

    if (getLastMessageId()
        != other.getLastMessageId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LASTMESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastMessageId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static pro.yarns.api.v1.service.CheckMessagesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static pro.yarns.api.v1.service.CheckMessagesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static pro.yarns.api.v1.service.CheckMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pro.yarns.api.v1.service.CheckMessagesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pro.yarns.api.v1.service.CheckMessagesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pro.yarns.api.v1.service.CheckMessagesRequest)
      pro.yarns.api.v1.service.CheckMessagesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pro.yarns.api.v1.service.CheckMessagesRequest.class, pro.yarns.api.v1.service.CheckMessagesRequest.Builder.class);
    }

    // Construct using pro.yarns.api.v1.service.CheckMessagesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lastMessageId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_descriptor;
    }

    @java.lang.Override
    public pro.yarns.api.v1.service.CheckMessagesRequest getDefaultInstanceForType() {
      return pro.yarns.api.v1.service.CheckMessagesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public pro.yarns.api.v1.service.CheckMessagesRequest build() {
      pro.yarns.api.v1.service.CheckMessagesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pro.yarns.api.v1.service.CheckMessagesRequest buildPartial() {
      pro.yarns.api.v1.service.CheckMessagesRequest result = new pro.yarns.api.v1.service.CheckMessagesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(pro.yarns.api.v1.service.CheckMessagesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lastMessageId_ = lastMessageId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pro.yarns.api.v1.service.CheckMessagesRequest) {
        return mergeFrom((pro.yarns.api.v1.service.CheckMessagesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pro.yarns.api.v1.service.CheckMessagesRequest other) {
      if (other == pro.yarns.api.v1.service.CheckMessagesRequest.getDefaultInstance()) return this;
      if (other.getLastMessageId() != 0L) {
        setLastMessageId(other.getLastMessageId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              lastMessageId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long lastMessageId_ ;
    /**
     * <code>int64 lastMessageId = 1 [json_name = "lastMessageId"];</code>
     * @return The lastMessageId.
     */
    @java.lang.Override
    public long getLastMessageId() {
      return lastMessageId_;
    }
    /**
     * <code>int64 lastMessageId = 1 [json_name = "lastMessageId"];</code>
     * @param value The lastMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setLastMessageId(long value) {

      lastMessageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 lastMessageId = 1 [json_name = "lastMessageId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLastMessageId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lastMessageId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pro.yarns.api.v1.service.CheckMessagesRequest)
  }

  // @@protoc_insertion_point(class_scope:pro.yarns.api.v1.service.CheckMessagesRequest)
  private static final pro.yarns.api.v1.service.CheckMessagesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pro.yarns.api.v1.service.CheckMessagesRequest();
  }

  public static pro.yarns.api.v1.service.CheckMessagesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckMessagesRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckMessagesRequest>() {
    @java.lang.Override
    public CheckMessagesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckMessagesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckMessagesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pro.yarns.api.v1.service.CheckMessagesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

