// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.service;

@com.google.protobuf.Generated
public interface CheckMessagesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pro.yarns.api.v1.service.CheckMessagesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 lastMessageId = 1 [json_name = "lastMessageId"];</code>
   * @return The lastMessageId.
   */
  long getLastMessageId();
}
