// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializecheckMessagesResponse")
public inline fun checkMessagesResponse(block: pro.yarns.api.v1.service.CheckMessagesResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.CheckMessagesResponse =
  pro.yarns.api.v1.service.CheckMessagesResponseKt.Dsl._create(pro.yarns.api.v1.service.CheckMessagesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.CheckMessagesResponse`
 */
public object CheckMessagesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.CheckMessagesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.CheckMessagesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.CheckMessagesResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MessagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .pro.yarns.api.v1.entity.Message messages = 1 [json_name = "messages"];`
     */
     public val messages: com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.MessageOuterClass.Message, MessagesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.messagesList
      )
    /**
     * `repeated .pro.yarns.api.v1.entity.Message messages = 1 [json_name = "messages"];`
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addMessages")
    public fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.MessageOuterClass.Message, MessagesProxy>.add(value: pro.yarns.api.v1.entity.MessageOuterClass.Message) {
      _builder.addMessages(value)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.Message messages = 1 [json_name = "messages"];`
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignMessages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.MessageOuterClass.Message, MessagesProxy>.plusAssign(value: pro.yarns.api.v1.entity.MessageOuterClass.Message) {
      add(value)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.Message messages = 1 [json_name = "messages"];`
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllMessages")
    public fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.MessageOuterClass.Message, MessagesProxy>.addAll(values: kotlin.collections.Iterable<pro.yarns.api.v1.entity.MessageOuterClass.Message>) {
      _builder.addAllMessages(values)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.Message messages = 1 [json_name = "messages"];`
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllMessages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.MessageOuterClass.Message, MessagesProxy>.plusAssign(values: kotlin.collections.Iterable<pro.yarns.api.v1.entity.MessageOuterClass.Message>) {
      addAll(values)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.Message messages = 1 [json_name = "messages"];`
     * @param index The index to set the value at.
     * @param value The messages to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMessages")
    public operator fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.MessageOuterClass.Message, MessagesProxy>.set(index: kotlin.Int, value: pro.yarns.api.v1.entity.MessageOuterClass.Message) {
      _builder.setMessages(index, value)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.Message messages = 1 [json_name = "messages"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMessages")
    public fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.MessageOuterClass.Message, MessagesProxy>.clear() {
      _builder.clearMessages()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.CheckMessagesResponse.copy(block: `pro.yarns.api.v1.service`.CheckMessagesResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.CheckMessagesResponse =
  `pro.yarns.api.v1.service`.CheckMessagesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

