// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializecheckMessagesRequest")
public inline fun checkMessagesRequest(block: pro.yarns.api.v1.service.CheckMessagesRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.CheckMessagesRequest =
  pro.yarns.api.v1.service.CheckMessagesRequestKt.Dsl._create(pro.yarns.api.v1.service.CheckMessagesRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.CheckMessagesRequest`
 */
public object CheckMessagesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.CheckMessagesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.CheckMessagesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.CheckMessagesRequest = _builder.build()

    /**
     * `int64 lastMessageId = 1 [json_name = "lastMessageId"];`
     */
    public var lastMessageId: kotlin.Long
      @kotlin.jvm.JvmName("getLastMessageId")
        get() = _builder.lastMessageId
      @kotlin.jvm.JvmName("setLastMessageId")
        set(value) {
        _builder.lastMessageId = value
      }
    /**
     * `int64 lastMessageId = 1 [json_name = "lastMessageId"];`
     */
    public fun clearLastMessageId() {
      _builder.clearLastMessageId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.CheckMessagesRequest.copy(block: `pro.yarns.api.v1.service`.CheckMessagesRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.CheckMessagesRequest =
  `pro.yarns.api.v1.service`.CheckMessagesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

