// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializeconfirmMessagesRequest")
public inline fun confirmMessagesRequest(block: pro.yarns.api.v1.service.ConfirmMessagesRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.ConfirmMessagesRequest =
  pro.yarns.api.v1.service.ConfirmMessagesRequestKt.Dsl._create(pro.yarns.api.v1.service.ConfirmMessagesRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.ConfirmMessagesRequest`
 */
public object ConfirmMessagesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.ConfirmMessagesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.ConfirmMessagesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.ConfirmMessagesRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MessageIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated int64 messageIds = 1 [json_name = "messageIds"];`
     */
     public val messageIds: com.google.protobuf.kotlin.DslList<kotlin.Long, MessageIdsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.messageIdsList
      )
    /**
     * `repeated int64 messageIds = 1 [json_name = "messageIds"];`
     * @param value The messageIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addMessageIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Long, MessageIdsProxy>.add(value: kotlin.Long) {
      _builder.addMessageIds(value)
    }/**
     * `repeated int64 messageIds = 1 [json_name = "messageIds"];`
     * @param value The messageIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignMessageIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, MessageIdsProxy>.plusAssign(value: kotlin.Long) {
      add(value)
    }/**
     * `repeated int64 messageIds = 1 [json_name = "messageIds"];`
     * @param values The messageIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllMessageIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Long, MessageIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Long>) {
      _builder.addAllMessageIds(values)
    }/**
     * `repeated int64 messageIds = 1 [json_name = "messageIds"];`
     * @param values The messageIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllMessageIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, MessageIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Long>) {
      addAll(values)
    }/**
     * `repeated int64 messageIds = 1 [json_name = "messageIds"];`
     * @param index The index to set the value at.
     * @param value The messageIds to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMessageIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, MessageIdsProxy>.set(index: kotlin.Int, value: kotlin.Long) {
      _builder.setMessageIds(index, value)
    }/**
     * `repeated int64 messageIds = 1 [json_name = "messageIds"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMessageIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Long, MessageIdsProxy>.clear() {
      _builder.clearMessageIds()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.ConfirmMessagesRequest.copy(block: `pro.yarns.api.v1.service`.ConfirmMessagesRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.ConfirmMessagesRequest =
  `pro.yarns.api.v1.service`.ConfirmMessagesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

