// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializeconfirmReceiveResponse")
public inline fun confirmReceiveResponse(block: pro.yarns.api.v1.service.ConfirmReceiveResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.ConfirmReceiveResponse =
  pro.yarns.api.v1.service.ConfirmReceiveResponseKt.Dsl._create(pro.yarns.api.v1.service.ConfirmReceiveResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.ConfirmReceiveResponse`
 */
public object ConfirmReceiveResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.ConfirmReceiveResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.ConfirmReceiveResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.ConfirmReceiveResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.ConfirmReceiveResponse.copy(block: `pro.yarns.api.v1.service`.ConfirmReceiveResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.ConfirmReceiveResponse =
  `pro.yarns.api.v1.service`.ConfirmReceiveResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

