// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.service;

@com.google.protobuf.Generated
public interface ConfirmReceiveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pro.yarns.api.v1.service.ConfirmReceiveResponse)
    com.google.protobuf.MessageOrBuilder {
}
