// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.service;

@com.google.protobuf.Generated
public interface ConfirmReceiveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pro.yarns.api.v1.service.ConfirmReceiveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 messageIds = 1 [json_name = "messageIds"];</code>
   * @return A list containing the messageIds.
   */
  java.util.List<java.lang.Long> getMessageIdsList();
  /**
   * <code>repeated int64 messageIds = 1 [json_name = "messageIds"];</code>
   * @return The count of messageIds.
   */
  int getMessageIdsCount();
  /**
   * <code>repeated int64 messageIds = 1 [json_name = "messageIds"];</code>
   * @param index The index of the element to return.
   * @return The messageIds at the given index.
   */
  long getMessageIds(int index);
}
