// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializeconfirmMessagesResponse")
public inline fun confirmMessagesResponse(block: pro.yarns.api.v1.service.ConfirmMessagesResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.ConfirmMessagesResponse =
  pro.yarns.api.v1.service.ConfirmMessagesResponseKt.Dsl._create(pro.yarns.api.v1.service.ConfirmMessagesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.ConfirmMessagesResponse`
 */
public object ConfirmMessagesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.ConfirmMessagesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.ConfirmMessagesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.ConfirmMessagesResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.ConfirmMessagesResponse.copy(block: `pro.yarns.api.v1.service`.ConfirmMessagesResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.ConfirmMessagesResponse =
  `pro.yarns.api.v1.service`.ConfirmMessagesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

