// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.service;

@com.google.protobuf.Generated
public interface GetMessageByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pro.yarns.api.v1.service.GetMessageByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pro.yarns.api.v1.entity.Message message = 1 [json_name = "message"];</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.pro.yarns.api.v1.entity.Message message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  pro.yarns.api.v1.entity.MessageOuterClass.Message getMessage();
  /**
   * <code>.pro.yarns.api.v1.entity.Message message = 1 [json_name = "message"];</code>
   */
  pro.yarns.api.v1.entity.MessageOuterClass.MessageOrBuilder getMessageOrBuilder();
}
