// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializegetMessageByIdResponse")
public inline fun getMessageByIdResponse(block: pro.yarns.api.v1.service.GetMessageByIdResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.GetMessageByIdResponse =
  pro.yarns.api.v1.service.GetMessageByIdResponseKt.Dsl._create(pro.yarns.api.v1.service.GetMessageByIdResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.GetMessageByIdResponse`
 */
public object GetMessageByIdResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.GetMessageByIdResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.GetMessageByIdResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.GetMessageByIdResponse = _builder.build()

    /**
     * `.pro.yarns.api.v1.entity.Message message = 1 [json_name = "message"];`
     */
    public var message: pro.yarns.api.v1.entity.MessageOuterClass.Message
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `.pro.yarns.api.v1.entity.Message message = 1 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * `.pro.yarns.api.v1.entity.Message message = 1 [json_name = "message"];`
     * @return Whether the message field is set.
     */
    public fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }

    public val GetMessageByIdResponseKt.Dsl.messageOrNull: pro.yarns.api.v1.entity.MessageOuterClass.Message?
      get() = _builder.messageOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.GetMessageByIdResponse.copy(block: `pro.yarns.api.v1.service`.GetMessageByIdResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.GetMessageByIdResponse =
  `pro.yarns.api.v1.service`.GetMessageByIdResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val pro.yarns.api.v1.service.GetMessageByIdResponseOrBuilder.messageOrNull: pro.yarns.api.v1.entity.MessageOuterClass.Message?
  get() = if (hasMessage()) getMessage() else null

