// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializegetUserByIdRequest")
public inline fun getUserByIdRequest(block: pro.yarns.api.v1.service.GetUserByIdRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.GetUserByIdRequest =
  pro.yarns.api.v1.service.GetUserByIdRequestKt.Dsl._create(pro.yarns.api.v1.service.GetUserByIdRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.GetUserByIdRequest`
 */
public object GetUserByIdRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.GetUserByIdRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.GetUserByIdRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.GetUserByIdRequest = _builder.build()

    /**
     * `int64 userId = 1 [json_name = "userId"];`
     */
    public var userId: kotlin.Long
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `int64 userId = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.GetUserByIdRequest.copy(block: `pro.yarns.api.v1.service`.GetUserByIdRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.GetUserByIdRequest =
  `pro.yarns.api.v1.service`.GetUserByIdRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

