// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializegetUsersByIdsResponse")
public inline fun getUsersByIdsResponse(block: pro.yarns.api.v1.service.GetUsersByIdsResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.GetUsersByIdsResponse =
  pro.yarns.api.v1.service.GetUsersByIdsResponseKt.Dsl._create(pro.yarns.api.v1.service.GetUsersByIdsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.GetUsersByIdsResponse`
 */
public object GetUsersByIdsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.GetUsersByIdsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.GetUsersByIdsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.GetUsersByIdsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UserProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .pro.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     */
     public val user: com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.UserOuterClass.User, UserProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.userList
      )
    /**
     * `repeated .pro.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     * @param value The user to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addUser")
    public fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.UserOuterClass.User, UserProxy>.add(value: pro.yarns.api.v1.entity.UserOuterClass.User) {
      _builder.addUser(value)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     * @param value The user to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignUser")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.UserOuterClass.User, UserProxy>.plusAssign(value: pro.yarns.api.v1.entity.UserOuterClass.User) {
      add(value)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     * @param values The user to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllUser")
    public fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.UserOuterClass.User, UserProxy>.addAll(values: kotlin.collections.Iterable<pro.yarns.api.v1.entity.UserOuterClass.User>) {
      _builder.addAllUser(values)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     * @param values The user to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllUser")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.UserOuterClass.User, UserProxy>.plusAssign(values: kotlin.collections.Iterable<pro.yarns.api.v1.entity.UserOuterClass.User>) {
      addAll(values)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     * @param index The index to set the value at.
     * @param value The user to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setUser")
    public operator fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.UserOuterClass.User, UserProxy>.set(index: kotlin.Int, value: pro.yarns.api.v1.entity.UserOuterClass.User) {
      _builder.setUser(index, value)
    }
    /**
     * `repeated .pro.yarns.api.v1.entity.User user = 1 [json_name = "user"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearUser")
    public fun com.google.protobuf.kotlin.DslList<pro.yarns.api.v1.entity.UserOuterClass.User, UserProxy>.clear() {
      _builder.clearUser()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.GetUsersByIdsResponse.copy(block: `pro.yarns.api.v1.service`.GetUsersByIdsResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.GetUsersByIdsResponse =
  `pro.yarns.api.v1.service`.GetUsersByIdsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

