// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializeregisterUserRequest")
public inline fun registerUserRequest(block: pro.yarns.api.v1.service.RegisterUserRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.RegisterUserRequest =
  pro.yarns.api.v1.service.RegisterUserRequestKt.Dsl._create(pro.yarns.api.v1.service.RegisterUserRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.RegisterUserRequest`
 */
public object RegisterUserRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.RegisterUserRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.RegisterUserRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.RegisterUserRequest = _builder.build()

    /**
     * `bytes publicKey = 1 [json_name = "publicKey"];`
     */
    public var publicKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPublicKey")
        get() = _builder.publicKey
      @kotlin.jvm.JvmName("setPublicKey")
        set(value) {
        _builder.publicKey = value
      }
    /**
     * `bytes publicKey = 1 [json_name = "publicKey"];`
     */
    public fun clearPublicKey() {
      _builder.clearPublicKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.RegisterUserRequest.copy(block: `pro.yarns.api.v1.service`.RegisterUserRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.RegisterUserRequest =
  `pro.yarns.api.v1.service`.RegisterUserRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

