// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.service;

/**
 * Protobuf type {@code pro.yarns.api.v1.service.SendMessageRequest}
 */
@com.google.protobuf.Generated
public final class SendMessageRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:pro.yarns.api.v1.service.SendMessageRequest)
    SendMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      SendMessageRequest.class.getName());
  }
  // Use SendMessageRequest.newBuilder() to construct.
  private SendMessageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SendMessageRequest() {
    type_ = 0;
    encryptedMetadata_ = com.google.protobuf.ByteString.EMPTY;
    encryptedBody_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_SendMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_SendMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pro.yarns.api.v1.service.SendMessageRequest.class, pro.yarns.api.v1.service.SendMessageRequest.Builder.class);
  }

  public static final int TO_FIELD_NUMBER = 1;
  private long to_ = 0L;
  /**
   * <code>int64 to = 1 [json_name = "to"];</code>
   * @return The to.
   */
  @java.lang.Override
  public long getTo() {
    return to_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_ = 0;
  /**
   * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  @java.lang.Override public pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType getType() {
    pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType result = pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.forNumber(type_);
    return result == null ? pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.UNRECOGNIZED : result;
  }

  public static final int ENCRYPTEDMETADATA_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString encryptedMetadata_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes encryptedMetadata = 3 [json_name = "encryptedMetadata"];</code>
   * @return The encryptedMetadata.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedMetadata() {
    return encryptedMetadata_;
  }

  public static final int ENCRYPTEDBODY_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString encryptedBody_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes encryptedBody = 4 [json_name = "encryptedBody"];</code>
   * @return The encryptedBody.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedBody() {
    return encryptedBody_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (to_ != 0L) {
      output.writeInt64(1, to_);
    }
    if (type_ != pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.MESSAGE_TYPE_UNKNOWN.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (!encryptedMetadata_.isEmpty()) {
      output.writeBytes(3, encryptedMetadata_);
    }
    if (!encryptedBody_.isEmpty()) {
      output.writeBytes(4, encryptedBody_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (to_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, to_);
    }
    if (type_ != pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.MESSAGE_TYPE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (!encryptedMetadata_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, encryptedMetadata_);
    }
    if (!encryptedBody_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, encryptedBody_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pro.yarns.api.v1.service.SendMessageRequest)) {
      return super.equals(obj);
    }
    pro.yarns.api.v1.service.SendMessageRequest other = (pro.yarns.api.v1.service.SendMessageRequest) obj;

    if (getTo()
        != other.getTo()) return false;
    if (type_ != other.type_) return false;
    if (!getEncryptedMetadata()
        .equals(other.getEncryptedMetadata())) return false;
    if (!getEncryptedBody()
        .equals(other.getEncryptedBody())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTo());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ENCRYPTEDMETADATA_FIELD_NUMBER;
    hash = (53 * hash) + getEncryptedMetadata().hashCode();
    hash = (37 * hash) + ENCRYPTEDBODY_FIELD_NUMBER;
    hash = (53 * hash) + getEncryptedBody().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static pro.yarns.api.v1.service.SendMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static pro.yarns.api.v1.service.SendMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static pro.yarns.api.v1.service.SendMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pro.yarns.api.v1.service.SendMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pro.yarns.api.v1.service.SendMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pro.yarns.api.v1.service.SendMessageRequest)
      pro.yarns.api.v1.service.SendMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_SendMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_SendMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pro.yarns.api.v1.service.SendMessageRequest.class, pro.yarns.api.v1.service.SendMessageRequest.Builder.class);
    }

    // Construct using pro.yarns.api.v1.service.SendMessageRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      to_ = 0L;
      type_ = 0;
      encryptedMetadata_ = com.google.protobuf.ByteString.EMPTY;
      encryptedBody_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pro.yarns.api.v1.service.ServiceProto.internal_static_pro_yarns_api_v1_service_SendMessageRequest_descriptor;
    }

    @java.lang.Override
    public pro.yarns.api.v1.service.SendMessageRequest getDefaultInstanceForType() {
      return pro.yarns.api.v1.service.SendMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public pro.yarns.api.v1.service.SendMessageRequest build() {
      pro.yarns.api.v1.service.SendMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pro.yarns.api.v1.service.SendMessageRequest buildPartial() {
      pro.yarns.api.v1.service.SendMessageRequest result = new pro.yarns.api.v1.service.SendMessageRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(pro.yarns.api.v1.service.SendMessageRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.to_ = to_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.encryptedMetadata_ = encryptedMetadata_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.encryptedBody_ = encryptedBody_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pro.yarns.api.v1.service.SendMessageRequest) {
        return mergeFrom((pro.yarns.api.v1.service.SendMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pro.yarns.api.v1.service.SendMessageRequest other) {
      if (other == pro.yarns.api.v1.service.SendMessageRequest.getDefaultInstance()) return this;
      if (other.getTo() != 0L) {
        setTo(other.getTo());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getEncryptedMetadata().isEmpty()) {
        setEncryptedMetadata(other.getEncryptedMetadata());
      }
      if (!other.getEncryptedBody().isEmpty()) {
        setEncryptedBody(other.getEncryptedBody());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              to_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              encryptedMetadata_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              encryptedBody_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long to_ ;
    /**
     * <code>int64 to = 1 [json_name = "to"];</code>
     * @return The to.
     */
    @java.lang.Override
    public long getTo() {
      return to_;
    }
    /**
     * <code>int64 to = 1 [json_name = "to"];</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(long value) {

      to_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 to = 1 [json_name = "to"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      to_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override
    public pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType getType() {
      pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType result = pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.forNumber(type_);
      return result == null ? pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encryptedMetadata_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encryptedMetadata = 3 [json_name = "encryptedMetadata"];</code>
     * @return The encryptedMetadata.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedMetadata() {
      return encryptedMetadata_;
    }
    /**
     * <code>bytes encryptedMetadata = 3 [json_name = "encryptedMetadata"];</code>
     * @param value The encryptedMetadata to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedMetadata(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      encryptedMetadata_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bytes encryptedMetadata = 3 [json_name = "encryptedMetadata"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedMetadata() {
      bitField0_ = (bitField0_ & ~0x00000004);
      encryptedMetadata_ = getDefaultInstance().getEncryptedMetadata();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encryptedBody_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encryptedBody = 4 [json_name = "encryptedBody"];</code>
     * @return The encryptedBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedBody() {
      return encryptedBody_;
    }
    /**
     * <code>bytes encryptedBody = 4 [json_name = "encryptedBody"];</code>
     * @param value The encryptedBody to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedBody(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      encryptedBody_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bytes encryptedBody = 4 [json_name = "encryptedBody"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedBody() {
      bitField0_ = (bitField0_ & ~0x00000008);
      encryptedBody_ = getDefaultInstance().getEncryptedBody();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pro.yarns.api.v1.service.SendMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:pro.yarns.api.v1.service.SendMessageRequest)
  private static final pro.yarns.api.v1.service.SendMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pro.yarns.api.v1.service.SendMessageRequest();
  }

  public static pro.yarns.api.v1.service.SendMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendMessageRequest>() {
    @java.lang.Override
    public SendMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SendMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pro.yarns.api.v1.service.SendMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

