// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializesendMessageResponse")
public inline fun sendMessageResponse(block: pro.yarns.api.v1.service.SendMessageResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.SendMessageResponse =
  pro.yarns.api.v1.service.SendMessageResponseKt.Dsl._create(pro.yarns.api.v1.service.SendMessageResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.SendMessageResponse`
 */
public object SendMessageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.SendMessageResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.SendMessageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.SendMessageResponse = _builder.build()

    /**
     * `int64 messageId = 1 [json_name = "messageId"];`
     */
    public var messageId: kotlin.Long
      @kotlin.jvm.JvmName("getMessageId")
        get() = _builder.messageId
      @kotlin.jvm.JvmName("setMessageId")
        set(value) {
        _builder.messageId = value
      }
    /**
     * `int64 messageId = 1 [json_name = "messageId"];`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.SendMessageResponse.copy(block: `pro.yarns.api.v1.service`.SendMessageResponseKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.SendMessageResponse =
  `pro.yarns.api.v1.service`.SendMessageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

