// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pro.yarns.api.v1.service;

@kotlin.jvm.JvmName("-initializesendMessageRequest")
public inline fun sendMessageRequest(block: pro.yarns.api.v1.service.SendMessageRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.SendMessageRequest =
  pro.yarns.api.v1.service.SendMessageRequestKt.Dsl._create(pro.yarns.api.v1.service.SendMessageRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pro.yarns.api.v1.service.SendMessageRequest`
 */
public object SendMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pro.yarns.api.v1.service.SendMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: pro.yarns.api.v1.service.SendMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): pro.yarns.api.v1.service.SendMessageRequest = _builder.build()

    /**
     * `int64 to = 1 [json_name = "to"];`
     */
    public var to: kotlin.Long
      @kotlin.jvm.JvmName("getTo")
        get() = _builder.to
      @kotlin.jvm.JvmName("setTo")
        set(value) {
        _builder.to = value
      }
    /**
     * `int64 to = 1 [json_name = "to"];`
     */
    public fun clearTo() {
      _builder.clearTo()
    }

    /**
     * `.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];`
     */
    public var type: pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * `.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `bytes encryptedMetadata = 3 [json_name = "encryptedMetadata"];`
     */
    public var encryptedMetadata: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getEncryptedMetadata")
        get() = _builder.encryptedMetadata
      @kotlin.jvm.JvmName("setEncryptedMetadata")
        set(value) {
        _builder.encryptedMetadata = value
      }
    /**
     * `bytes encryptedMetadata = 3 [json_name = "encryptedMetadata"];`
     */
    public fun clearEncryptedMetadata() {
      _builder.clearEncryptedMetadata()
    }

    /**
     * `bytes encryptedBody = 4 [json_name = "encryptedBody"];`
     */
    public var encryptedBody: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getEncryptedBody")
        get() = _builder.encryptedBody
      @kotlin.jvm.JvmName("setEncryptedBody")
        set(value) {
        _builder.encryptedBody = value
      }
    /**
     * `bytes encryptedBody = 4 [json_name = "encryptedBody"];`
     */
    public fun clearEncryptedBody() {
      _builder.clearEncryptedBody()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pro.yarns.api.v1.service.SendMessageRequest.copy(block: `pro.yarns.api.v1.service`.SendMessageRequestKt.Dsl.() -> kotlin.Unit): pro.yarns.api.v1.service.SendMessageRequest =
  `pro.yarns.api.v1.service`.SendMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

