// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.service;

@com.google.protobuf.Generated
public interface SendMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pro.yarns.api.v1.service.SendMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 to = 1 [json_name = "to"];</code>
   * @return The to.
   */
  long getTo();

  /**
   * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.pro.yarns.api.v1.entity.MessageType type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  pro.yarns.api.v1.entity.MessageTypeOuterClass.MessageType getType();

  /**
   * <code>bytes encryptedMetadata = 3 [json_name = "encryptedMetadata"];</code>
   * @return The encryptedMetadata.
   */
  com.google.protobuf.ByteString getEncryptedMetadata();

  /**
   * <code>bytes encryptedBody = 4 [json_name = "encryptedBody"];</code>
   * @return The encryptedBody.
   */
  com.google.protobuf.ByteString getEncryptedBody();
}
