// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/service/service.proto
// Protobuf Java Version: 4.31.1

package pro.yarns.api.v1.service;

@com.google.protobuf.Generated
public final class ServiceProto {
  private ServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_RegisterUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_RegisterUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_RegisterUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_RegisterUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_GetUsersByIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_GetUsersByIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_GetUsersByIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_GetUsersByIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_SendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_SendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_CheckMessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_CheckMessagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_ConfirmMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_ConfirmMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pro_yarns_api_v1_service_ConfirmMessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pro_yarns_api_v1_service_ConfirmMessagesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030v1/service/service.proto\022\030pro.yarns.ap" +
      "i.v1.service\032\024v1/entity/user.proto\032\027v1/e" +
      "ntity/message.proto\032\034v1/entity/message_t" +
      "ype.proto\"3\n\023RegisterUserRequest\022\034\n\tpubl" +
      "icKey\030\001 \001(\014R\tpublicKey\"I\n\024RegisterUserRe" +
      "sponse\0221\n\004user\030\001 \001(\0132\035.pro.yarns.api.v1." +
      "entity.UserR\004user\"0\n\024GetUsersByIdsReques" +
      "t\022\030\n\007userIds\030\001 \003(\003R\007userIds\"J\n\025GetUsersB" +
      "yIdsResponse\0221\n\004user\030\001 \003(\0132\035.pro.yarns.a" +
      "pi.v1.entity.UserR\004user\"\262\001\n\022SendMessageR" +
      "equest\022\016\n\002to\030\001 \001(\003R\002to\0228\n\004type\030\002 \001(\0162$.p" +
      "ro.yarns.api.v1.entity.MessageTypeR\004type" +
      "\022,\n\021encryptedMetadata\030\003 \001(\014R\021encryptedMe" +
      "tadata\022$\n\rencryptedBody\030\004 \001(\014R\rencrypted" +
      "Body\"3\n\023SendMessageResponse\022\034\n\tmessageId" +
      "\030\001 \001(\003R\tmessageId\"<\n\024CheckMessagesReques" +
      "t\022$\n\rlastMessageId\030\001 \001(\003R\rlastMessageId\"" +
      "U\n\025CheckMessagesResponse\022<\n\010messages\030\001 \003" +
      "(\0132 .pro.yarns.api.v1.entity.MessageR\010me" +
      "ssages\"8\n\026ConfirmMessagesRequest\022\036\n\nmess" +
      "ageIds\030\001 \003(\003R\nmessageIds\"\031\n\027ConfirmMessa" +
      "gesResponse2\303\004\n\nYarnsApiV1\022m\n\014RegisterUs" +
      "er\022-.pro.yarns.api.v1.service.RegisterUs" +
      "erRequest\032..pro.yarns.api.v1.service.Reg" +
      "isterUserResponse\022p\n\rGetUsersByIds\022..pro" +
      ".yarns.api.v1.service.GetUsersByIdsReque" +
      "st\032/.pro.yarns.api.v1.service.GetUsersBy" +
      "IdsResponse\022j\n\013SendMessage\022,.pro.yarns.a" +
      "pi.v1.service.SendMessageRequest\032-.pro.y" +
      "arns.api.v1.service.SendMessageResponse\022" +
      "p\n\rCheckMessages\022..pro.yarns.api.v1.serv" +
      "ice.CheckMessagesRequest\032/.pro.yarns.api" +
      ".v1.service.CheckMessagesResponse\022v\n\017Con" +
      "firmMessages\0220.pro.yarns.api.v1.service." +
      "ConfirmMessagesRequest\0321.pro.yarns.api.v" +
      "1.service.ConfirmMessagesResponseBV\n\030pro" +
      ".yarns.api.v1.serviceB\014ServiceProtoP\001Z*g" +
      "ithub.com/yarns-pro/api/pkg/go/v1/servic" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pro.yarns.api.v1.entity.UserOuterClass.getDescriptor(),
          pro.yarns.api.v1.entity.MessageOuterClass.getDescriptor(),
          pro.yarns.api.v1.entity.MessageTypeOuterClass.getDescriptor(),
        });
    internal_static_pro_yarns_api_v1_service_RegisterUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pro_yarns_api_v1_service_RegisterUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_RegisterUserRequest_descriptor,
        new java.lang.String[] { "PublicKey", });
    internal_static_pro_yarns_api_v1_service_RegisterUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pro_yarns_api_v1_service_RegisterUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_RegisterUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_pro_yarns_api_v1_service_GetUsersByIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pro_yarns_api_v1_service_GetUsersByIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_GetUsersByIdsRequest_descriptor,
        new java.lang.String[] { "UserIds", });
    internal_static_pro_yarns_api_v1_service_GetUsersByIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pro_yarns_api_v1_service_GetUsersByIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_GetUsersByIdsResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_pro_yarns_api_v1_service_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pro_yarns_api_v1_service_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_SendMessageRequest_descriptor,
        new java.lang.String[] { "To", "Type", "EncryptedMetadata", "EncryptedBody", });
    internal_static_pro_yarns_api_v1_service_SendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pro_yarns_api_v1_service_SendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_SendMessageResponse_descriptor,
        new java.lang.String[] { "MessageId", });
    internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_CheckMessagesRequest_descriptor,
        new java.lang.String[] { "LastMessageId", });
    internal_static_pro_yarns_api_v1_service_CheckMessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pro_yarns_api_v1_service_CheckMessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_CheckMessagesResponse_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_pro_yarns_api_v1_service_ConfirmMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_pro_yarns_api_v1_service_ConfirmMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_ConfirmMessagesRequest_descriptor,
        new java.lang.String[] { "MessageIds", });
    internal_static_pro_yarns_api_v1_service_ConfirmMessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_pro_yarns_api_v1_service_ConfirmMessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pro_yarns_api_v1_service_ConfirmMessagesResponse_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    pro.yarns.api.v1.entity.UserOuterClass.getDescriptor();
    pro.yarns.api.v1.entity.MessageOuterClass.getDescriptor();
    pro.yarns.api.v1.entity.MessageTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
