// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/entity/user.proto
// Protobuf Java Version: 4.31.1

package ru.kamenetskii.yarns.api.v1.entity;

@com.google.protobuf.Generated
public final class EntityProto {
  private EntityProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      EntityProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_kamenetskii_yarns_api_v1_entity_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_kamenetskii_yarns_api_v1_entity_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024v1/entity/user.proto\022\"ru.kamenetskii.y" +
      "arns.api.v1.entity\032\037google/protobuf/time" +
      "stamp.proto\"\246\001\n\004User\022\016\n\002id\030\001 \001(\003R\002id\022\034\n\t" +
      "publicKey\030\002 \001(\014R\tpublicKey\0228\n\tcreatedAt\030" +
      "\003 \001(\0132\032.google.protobuf.TimestampR\tcreat" +
      "edAt\0226\n\010activeAt\030\004 \001(\0132\032.google.protobuf" +
      ".TimestampR\010activeAtB^\n\"ru.kamenetskii.y" +
      "arns.api.v1.entityB\013EntityProtoP\001Z)githu" +
      "b.com/yarns-pro/api/pkg/go/v1/entityb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ru_kamenetskii_yarns_api_v1_entity_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_kamenetskii_yarns_api_v1_entity_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_kamenetskii_yarns_api_v1_entity_User_descriptor,
        new java.lang.String[] { "Id", "PublicKey", "CreatedAt", "ActiveAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
